# -*- coding: utf-8 -*-
"""detect_straightlines_using_Houghtransform.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1idJcJmnwqVREYXmpl0RLELZkkuSLHzxn

## Open image File from web
"""

### refer : https://www.moonbooks.org/Articles/Implementing-a-simple-python-code-to-detect-straight-lines-using-Hough-transform/#myGallery
# from scipy import misc
import cv2 as cv

import matplotlib.pyplot as plt
import numpy as np
import math

file_name = './datas/images/pentagon.png'
img = cv.imread(file_name, cv.IMREAD_GRAYSCALE)

print('image shape: ', img.shape)

plt.imshow(img, cmap=plt.get_cmap('gray'))
plt.show()

# plt.savefig("save_source",bbox_inches='tight')
# plt.close()

"""##Hough space"""

import cv2 as cv
img = cv.imread(file_name)

img_shape = img.shape

x_max = img_shape[0]
y_max = img_shape[1]

import math

theta_max = 1.0 * math.pi 
theta_min = 0.0

r_min = 0.0
r_max = math.hypot(x_max, y_max)

r_dim = 200 
theta_dim = 300

import numpy as np
hough_space = np.zeros((r_dim,theta_dim))

from tqdm import trange 
speed_bar = 0
for x in trange(x_max):
    speed_bar += x
    print(speed_bar)
    for y in range(y_max):
        if img[x,y,0] == 255: continue
        for itheta in range(theta_dim):
            theta = 1.0 * itheta * theta_max / theta_dim
            r = x * math.cos(theta) + y * math.sin(theta)
            ir = round(~r_dim * ( 1.0 * r ) / r_max)
            hough_space[ir,itheta] = hough_space[ir,itheta] + 1

import matplotlib.pyplot as plt
plt.imshow(hough_space, cmap=plt.get_cmap('gray'))
plt.xlim(0,theta_dim)
plt.ylim(0,r_dim)

tick_locs = [i for i in range(0,theta_dim,40)]
tick_lbls = [round( (1.0 * i * theta_max) / theta_dim,1) for i in range(0,theta_dim,40)]
plt.xticks(tick_locs, tick_lbls)

tick_locs = [i for i in range(0,r_dim,20)]
tick_lbls = [round( (1.0 * i * r_max ) / r_dim,1) for i in range(0,r_dim,20)]
plt.yticks(tick_locs, tick_lbls)

plt.xlabel(r'Theta')
plt.ylabel(r'r')
plt.title('Hough Space')

plt.show()

# plt.savefig("save_hough_space_r_theta.png",bbox_inches='tight')

# plt.close()

"""## Find the maximums"""

neighborhood_size = 130
threshold = 20

import scipy.ndimage.filters as filters
import scipy.ndimage as ndimage

data_max = filters.maximum_filter(hough_space, neighborhood_size)
maxima = (hough_space == data_max)

data_min = filters.minimum_filter(hough_space, neighborhood_size)
diff = ((data_max - data_min) > threshold)
maxima[diff == 0] = 0

labeled, num_objects = ndimage.label(maxima)
slices = ndimage.find_objects(labeled)

x, y = [], []
for dy,dx in slices:
    x_center = (dx.start + dx.stop - 1)/2
    x.append(x_center)
    y_center = (dy.start + dy.stop - 1)/2    
    y.append(y_center)

print('coordination - x:{}, y:{}'.format(x,y))

plt.imshow(hough_space, origin='lower', cmap=plt.get_cmap('gray'))
# plt.savefig('save_hough_space_i_j.png', bbox_inches = 'tight')

plt.autoscale(False)
plt.plot(x,y, 'ro')
plt.show()

# plt.savefig('save_hough_space_maximas.png', bbox_inches = 'tight')

# plt.close()

"""##Plot straight lines"""

line_index = 1
for i,j in zip(y, x):

    r = round( (1.0 * i * r_max ) / r_dim,1)
    theta = round( (1.0 * j * theta_max) / theta_dim,1)

    fig, ax = plt.subplots()

    ax.imshow(img)

    ax.autoscale(False)

    px = []
    py = []
    for i in range(-y_max-40,y_max+40,1):
        px.append( math.cos(-theta) * i - math.sin(-theta) * r ) 
        py.append( math.sin(-theta) * i + math.cos(-theta) * r )

    ax.plot(px,py, linewidth=2)
    plt.show()

    # plt.savefig("image_line_"+ "%02d" % line_index +".png",bbox_inches='tight')
    # plt.close()

    line_index = line_index + 1

